import {
    Upload,
    Download,
    Settings,
    Search,
    Share2,
    Trash2,
    Copy,
    Edit,
    CheckCircle2,
    XCircle,
    Plus,
    Minus,
    RefreshCw,
    Globe,
    Info,

    Image,
    FileCheck,
    Gauge,
    Wand2,
    Palette,
    MoveHorizontal,
    MoveVertical,
    Film,
    Clapperboard,
    Video,
    ArrowRightLeft,
    FileText,
    Files, BookOpen,
    Scissors,
    Volume2,
    Music,
    Merge,
    Split,
    Layers,
    Crop,
    Sliders,
    Frame,
    Mic,
    AudioLines,
} from "lucide-react";

export const universalIcons = [
    Upload,
    Download,
    Settings,
    Search,
    Share2,
    Trash2,
    Copy,
    Edit,
    CheckCircle2,
    XCircle,
    Plus,
    Minus,
    RefreshCw,
    Globe,
    Info,
];

export const manualIcons = {
    convertImage: [Image, FileCheck, Layers],
    cropImage: [Scissors, Crop],
    compressImage: [Gauge, Sliders],
    filterImage: [Wand2, Palette, Frame],
    resizeImage: [MoveHorizontal, MoveVertical, Sliders],
    watermarkImage: [Image],
    enhanceImage: [Image],

    compressVideo: [Film, Gauge],
    clipVideo: [Scissors, Clapperboard, Frame],
    convertVideo: [Video, ArrowRightLeft],
    createThumbnail: [Video],

    convertPdf: [FileText, ArrowRightLeft],
    mergePdf: [Merge, Files, Layers],
    splitPdf: [Split, BookOpen],

    clipAudio: [Scissors, AudioLines],
    compressAudio: [Volume2, Sliders],
    convertAudio: [Music, ArrowRightLeft, Mic],
};